version: '3'

services:
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    ports:
      - '3003:3003'
    environment:
      - PGADMIN_LISTEN_PORT=3003
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    links:
      - cloud-sql-proxy-for-pg
    networks:
      - pgadmin4_pg

  cloud-sql-proxy-for-pg:
    container_name: cloud-sql-proxy-for-pg
    image: gcr.io/cloudsql-docker/gce-proxy:1.12
    command: /cloud_sql_proxy -instances=${INSTANCE_CONNECTION_NAME}=tcp:0.0.0.0:5432 -credential_file=/config
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/config
    networks:
      - pgadmin4_pg

networks:
  pgadmin4_pg:
    driver: 'bridge'
