version: '2'

services:
  web:
    extends: 
      file: docker-compose-base.yml
      service: webapp
    environment:
      - DEBUG=1
    depends_on:
      - redis

  redis:
    image: redis:alpine
    
    

    
    